---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: detect-private-key
    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
          - id: detect-secrets
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.7.0
      hooks:
          - id: nbqa-pyupgrade
          - id: nbqa-mypy
          - id: nbqa-flake8
          - id: nbqa-pydocstyle
          - id: nbqa-check-ast
          - id: nbqa-pyupgrade
          - id: nbqa-flake8
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.4
      hooks:
          - id: autopep8
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.5.1
      hooks:
          - id: mypy
    - repo: https://github.com/frnmst/md-toc
      rev: 8.2.0
      hooks:
          - id: md-toc
    - repo: https://github.com/peterdemin/pip-compile-multi
      rev: v2.6.3
      hooks:
          - id: pip-compile-multi-verify
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.10.1
      hooks:
          - id: pyupgrade
    - repo: https://github.com/asottile/yesqa
      rev: v1.5.0
      hooks:
          - id: yesqa
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
          - id: bandit
